#!/bin/sh

PATH=/usr/share/mle:${PATH}

ENCODE=0
INTERPRET=1

error()
{
	printf "%08x: %s\n" ${OFFSET} "$1" >&2
}

byte()
{
	printf $(printf "\%03o" $(($1 & 0xff)))
	OFFSET=$((OFFSET + 1))
}

u8()
{
	for value
	do
		byte $value
	done
}

u16le()
{
	for value
	do
		u8 $value $((value >> 8))
	done
}

u16be()
{
	for value
	do
		u8 $((value >> 8)) $value
	done
}

u32le()
{
	for value
	do
		u16le $value $((value >> 16))
	done
}

u32be()
{
	for value
	do
		u16be $((value >> 16)) $value
	done
}

u64le()
{
	for value
	do
		u32le $value $((value >> 32))
	done
}

u64be()
{
	for value
	do
		u32be $((value >> 32)) $value
	done
}

define()
{
	eval $1=$2
}

resolve()
{
	local label=$1
	local offset=0

	set -- $LABELS

	while [ $# -ge 2 ]
	do
		if [ "$label" = "$1" ]
		then
			offset=$2
			break
		fi

		shift 2
	done

	printf $offset
}

label()
{
	if [ $PASS -eq 1 ]
	then
		local label=$1
		set -- $LABELS

		while [ $# -ge 2 ]
		do
			if [ "$label" = "$1" ]
			then
				error "redefined label: $label"
				exit 1
			fi

			shift 2
		done

		LABELS="$LABELS $label $OFFSET"
	fi
}

macro()
{
	local token=$1
	shift 1

	MACROS="$token $MACROS"
	eval "${token}() { $@; }"
}

callable()
{
	local token=$1

	set -- $MACROS

	for macro
	do
		if [ $macro = $token ]
		then
			return 0
		fi
	done

	return 1
}

interpret()
{
	local token=$1
	shift 1

	if ! callable $token
	then
		error "unrecognized token: $token"
		exit 1
	fi

	$token $@
}

evaluate()
{
	for token
	do
		case $MODE in
		$ENCODE)
			case $token in
			'#')
				break
				;;
			'[')
				MODE=$INTERPRET
				;;
			*:)
				label ${token%%:}
				;;
			[0-f][0-f])
				byte 0x${token}
				;;
			esac
			;;
		$INTERPRET)
			case $token in
			']')
				interpret ${EXPRESSION}
				EXPRESSION=
				MODE=$ENCODE
				;;
			*)
				EXPRESSION="${EXPRESSION} ${token}"
				;;
			esac
			;;
		esac

		if [ $PASS -eq 1 ]
		then
			TOKENS="${TOKENS} ${token}"
		fi
	done
}

encode()
{
	MACROS="macro define resolve ."
	PASS=1
	OFFSET=0
	MODE=$ENCODE
	TOKENS=

	while read line
	do
		evaluate $line > /dev/null
	done

	MACROS="macro define resolve ."
	PASS=2
	OFFSET=0
	MODE=$ENCODE

	evaluate $TOKENS
}

map()
{
	set -- $LABELS

	while [ $# -ge 2 ]
	do
		printf "%08x %s\n" "$2" "$1"
		shift 2
	done > $MAP
}

usage()
{
	printf "usage: mle [-o OUTPUT] [-m MAP] [INPUT]\n"
}

main()
{
	while [ $# -gt 0 ]
	do
		case $1 in
		("-h")
			usage
			return 0
			;;
		("-o")
			if [ $# -eq 1 ]
			then
				usage
				return 1
			fi

			OUTPUT=$2
			shift 2
			;;

		("-m")
			if [ $# -eq 1 ]
			then
				usage
				return 1
			fi

			MAP=$2
			shift 2
			;;

		(*)
			if ! [ -f $1 ]
			then
				usage
				return 1
			fi

			INPUT=$1
			shift 1
			;;
		esac
	done

	if [ -n "$INPUT" ]
	then
		exec 0<"$INPUT"
	fi

	if [ -n "$OUTPUT" ]
	then
		exec 1>"$OUTPUT"
		chmod 755 "$OUTPUT"
	fi

	encode

	if [ -n "$MAP" ]
	then
		map
	fi
}

if [ $(basename $0) = "mle" ]
then
	main "$@"
fi
