#!/bin/sh

PROGRAM="mle"
MANUAL="mle.1"

PREFIX="${PREFIX:-/usr/local}"
PREFIX_BIN_DIR="${PREFIX}/bin"
PREFIX_MAN_DIR="${PREFIX}/share/man/man1"
PREFIX_SHARE_DIR="${PREFIX}/share/${PROGRAM}"

set -e

usage()
{
	printf "usage: setup {install|uninstall}\n"
}

install()
{
	set -x

	mkdir -p "${PREFIX_BIN_DIR}" "${PREFIX_SHARE_DIR}"
	sed -e "s,PREFIX:-/usr/local,PREFIX:-${PREFIX},g" "src/${PROGRAM}" \
	     > "${PREFIX_BIN_DIR}/${PROGRAM}"
	chmod 755 "${PREFIX_BIN_DIR}/${PROGRAM}"

	mkdir -p "${PREFIX_MAN_DIR}"
	cp "doc/${MANUAL}" "${PREFIX_MAN_DIR}/"
}

uninstall()
{
	set -x
	rm -f "${PREFIX_BIN_DIR}/${PROGRAM}" "${PREFIX_MAN_DIR}/${MANUAL}"
}

main()
{
	case $# in
	(1)
		case $1 in
		("install")
			install
			;;

		("uninstall")
			uninstall
			;;

		(*)
			usage
			;;
		esac
		;;

	(*)
		usage
		;;
	esac
}

main "$@"
